name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      environment: python3.9
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        PYTHON_VERSION: ${{secrets.PYTHON_VERSION}}
      run: docker build . --tag ${{secrets.DOCKER_USER}}/python-test:${{PYTHON_VERSION}}
    - name: docker push
      environment: python3.9
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        PYTHON_VERSION: ${{secrets.PYTHON_VERSION}}
      run: docker push ${{secrets.DOCKER_USER}}/python-test:${{PYTHON_VERSION}}
